### PR TITLE
Creation complete handler

### PR DESCRIPTION
**Pull request by redannick**
Creation complete convenience handler in View, with reference to https://github.com/mesmotronic/conbo/issues/1

### CODE REVIEW

**Comment by neilrackett** [comment]
Looks good.

Can you update the `View` class in the TypeScript definitions (`typings/conbo.d.ts`) with the new method too?

**Comment by redannick** [comment]
already there!

**Comment by neilrackett** [comment]
Missing (brackets) before `:void`

**Comment by redannick** [comment]
oops!

**Review by neilrackett — APPROVED** [review]

**Pull request merged**
